[[HelloWorldC]]
arch = "aarch64"
git-tree-sha1 = "99e62a0c64cf6767a97cc805321ff4257917c285"
os = "macos"

    [[HelloWorldC.download]]
    sha256 = "4382388ce3497d14963a25f400f51f6cdd8354fba927550f071b9f90c74fea1c"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.aarch64-apple-darwin.tar.gz"
[[HelloWorldC]]
arch = "aarch64"
git-tree-sha1 = "c82465bd6d0aa1369ff2fd961b73884d1f5de49a"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "5bfa84332c7ee485ca8e2eee216ad9fa77b2c43d5f261baa823e301b7c789ec4"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.aarch64-linux-gnu.tar.gz"
[[HelloWorldC]]
arch = "aarch64"
git-tree-sha1 = "cb4b8c88778c6cd93b6df38ec5b95a2678434f5d"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "924df1c2a386f79a2727a2f989393102649a24863214f2e88cb4a677d3d22e14"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.aarch64-linux-musl.tar.gz"
[[HelloWorldC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "20a32b71145b67e708f63fb5880a7243727aec0f"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "6f0997b0aad387ba6e2402530642bb4ded85b0243460d2e4b13d94f2c8340a44"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.armv6l-linux-gnueabihf.tar.gz"
[[HelloWorldC]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c1179604ea37fa66ee6d5d592c7bbfd1f20292c3"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "0aca47bce6f09c38a7939277a593deb988123fe59f7992225a1ede8e174f1b06"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.armv6l-linux-musleabihf.tar.gz"
[[HelloWorldC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0a8e7b523ef6be31311aefe9983a488616e58201"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "f29f4da556d2b4ee9eaff7740aa0f9436406b75b0f1ec428e881a47ab7b7477b"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.armv7l-linux-gnueabihf.tar.gz"
[[HelloWorldC]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ca94b4d87f1a276066a2994733142e35046c41dd"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "5fb4019d6d797e5e3860cfec90cab12f6865fa624e87b51c20220a44bb94846a"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.armv7l-linux-musleabihf.tar.gz"
[[HelloWorldC]]
arch = "i686"
git-tree-sha1 = "7063f79bec122879f7b497a1cad52171009b995f"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "40e6e46e50af3c5f3a700397ad3b724c0206315ddf050d3205570bf18d1b7a8b"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.i686-linux-gnu.tar.gz"
[[HelloWorldC]]
arch = "i686"
git-tree-sha1 = "b50220be02e9c839749f91a70694ae68c2712c8e"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "6aecc06cf803ad16703744610deb243a21b39e19ae1951a38977610881698f9e"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.i686-linux-musl.tar.gz"
[[HelloWorldC]]
arch = "i686"
git-tree-sha1 = "0f7597f042d16d438f9684e20ca57ea22e4e15c1"
os = "windows"

    [[HelloWorldC.download]]
    sha256 = "5f14f5ade1314e777432bd85cd075ae9d31e28352e646f90adf0444a7a54f76b"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.i686-w64-mingw32.tar.gz"
[[HelloWorldC]]
arch = "powerpc64le"
git-tree-sha1 = "5e9c87fc4e3372c27a77061a49d97fa5002df0e4"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "e2a728b29124fc7408d6e47cc6fc943d0336d1386e56a3775a0665b34528881b"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.powerpc64le-linux-gnu.tar.gz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "6535b0e10003ce22db71736128eeab24d03cfca4"
os = "macos"

    [[HelloWorldC.download]]
    sha256 = "18e034dc69d36e5880ad3581896b1955cf6abc292077eb6b43049279a96cfdce"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.x86_64-apple-darwin.tar.gz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "8c8251b0c21615bce0701995eded26ac7697b5cc"
libc = "glibc"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "974f7e1d1cdbebad149e51fed4f1b7c6a0b5ccfa350f7d252dfcf66c2dbf9f63"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.x86_64-linux-gnu.tar.gz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "cfaaf0517421585561e3b30dd6f53f6c14b2835f"
libc = "musl"
os = "linux"

    [[HelloWorldC.download]]
    sha256 = "25d3d6ecc753f4dbbcaab0db7b6c20b29b0a79b0c31f7a26a0cf18c365d27809"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.x86_64-linux-musl.tar.gz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "5911d97f09156c8e4e78e48941da48575e095040"
os = "freebsd"

    [[HelloWorldC.download]]
    sha256 = "5a27c8c476d399bd823e18cabd072f67e9b4b9904ddff3b553d0ed05c4ef7676"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.x86_64-unknown-freebsd.tar.gz"
[[HelloWorldC]]
arch = "x86_64"
git-tree-sha1 = "59955b315ce95abd82f71d29389be3b734b14821"
os = "windows"

    [[HelloWorldC.download]]
    sha256 = "47bbead5cbdfca1b23544b1b398e8a2194c78ab8a772ca3075084c4a9ab75fb7"
    url = "https://github.com/staticfloat/HelloWorldC_jll.jl/releases/download/HelloWorldC-v1.2.1+2/HelloWorldC.v1.2.1.x86_64-w64-mingw32.tar.gz"
