# Autogenerated wrapper script for HelloWorldC_jll for aarch64-linux-gnu
export hello_world

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "LD_LIBRARY_PATH"
LIBPATH_default = ""

# Relative path to `hello_world`
const hello_world_splitpath = ["bin", "hello_world"]

# This will be filled out by __init__() for all products, as it must be done at runtime
hello_world_path = ""

# hello_world-specific global declaration
function hello_world(f::Function; adjust_PATH::Bool = true, adjust_LIBPATH::Bool = true)
    global PATH, LIBPATH
    env_mapping = Dict{String,String}()
    if adjust_PATH
        if !isempty(get(ENV, "PATH", ""))
            env_mapping["PATH"] = string(PATH, ':', ENV["PATH"])
        else
            env_mapping["PATH"] = PATH
        end
    end
    if adjust_LIBPATH
        LIBPATH_base = get(ENV, LIBPATH_env, expanduser(LIBPATH_default))
        if !isempty(LIBPATH_base)
            env_mapping[LIBPATH_env] = string(LIBPATH, ':', LIBPATH_base)
        else
            env_mapping[LIBPATH_env] = LIBPATH
        end
    end
    withenv(env_mapping...) do
        f(hello_world_path)
    end
end


"""
Open all libraries
"""
function __init__()
    global artifact_dir = abspath(artifact"HelloWorldC")

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global hello_world_path = normpath(joinpath(artifact_dir, hello_world_splitpath...))

    push!(PATH_list, dirname(hello_world_path))
    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ':')
    global LIBPATH = join(vcat(LIBPATH_list, [joinpath(Sys.BINDIR, Base.LIBDIR, "julia"), joinpath(Sys.BINDIR, Base.LIBDIR)]), ':')

    ENV["JULIA_HELLO_WORLD"]="C"

end  # __init__()

